### ISSUE TITLE
Configuring Time Zone and URLs

### ISSUE THREAD

**Issue by mfehlhaber** [CU-CommunityApps/ct-az-common-alert-endpoint#191]
Currently the time zone is hard-coded to `America/New_York`, the time display not configurable (e.g. for military time), and links back to Azure Portal contain `cornellprod.onmicrosoft.com`.

You might wish to turn these into optional environment variables.

For Azure environments other then global/public, you'd also have to be able to configure the portal part of the URLs, e.g. `portal.azure.cn`

**Comment by mikesprague** [comment]
This project is a starting point for you to set your own endpoint up, not an endpoint that anyone can use. If you have not deployed it and set it up correctly, it will not work.

Once you have your own copy, you can change any of the code (including the timezone and any URLs).
