### ISSUE TITLE
Fallback should show essentials

### ISSUE THREAD

**Issue by mfehlhaber** [CU-CommunityApps/ct-az-common-alert-endpoint#192]
Currently, when no `adaptiveCard` was created before, the fallback card created is rather basic. Since you already tested for `req.body.data.essentials`, you could just as well use these and show them nicely. Full JSON could be hidden behind a button, maybe.

Thank you for your great work. I'm glad I stumbled upon it when researching what others are doing to get Azure Alerts as Adaptive Cards into Teams.

**Comment by mikesprague** [comment]
Feel free to submit a pull request with your desired behavior and/or to fork the repo and make any changes you want in your own copy. This is working as intended for our purposes. 

This project is intended to be a starter to help people set their own endpoints up. Feel free to make any changes that fit your needs once you have done so.
